apiVersion: tekton.dev/v1
kind: Pipeline

metadata:
  name: dotnet-ci
  namespace: cicd-poc

spec:
  params:

    - name: GIT_URL
      type: string

    - name: GIT_REVISION
      type: string
      default: main

    - name: DOTNET_IMAGE
      type: string

    - name: S2I_IMAGE
      type: string

    - name: S2I_BUILDER_IMAGE
      type: string

    - name: BUILDAH_IMAGE
      type: string

    - name: APPLICATION_IMAGE
      type: string

    - name: PROJECT_PATH
      type: string
      default: "."

  workspaces:
    - name: shared-workspace

  tasks:

    # -------------------------
    # 1. Clone
    # -------------------------
    - name: clone
      taskRef:
        name: git-clone

      params:
        - name: url
          value: "$(params.GIT_URL)"

        - name: revision
          value: "$(params.GIT_REVISION)"

      workspaces:
        - name: output
          workspace: shared-workspace

    # -------------------------
    # 2. .NET Build
    # -------------------------
    - name: build
      runAfter:
        - clone

      taskRef:
        name: dotnet-build

      params:
        - name: DOTNET_IMAGE
          value: "$(params.DOTNET_IMAGE)"

        - name: PROJECT_PATH
          value: "$(params.PROJECT_PATH)"

      workspaces:
        - name: source
          workspace: shared-workspace

    # -------------------------
    # 3. S2I + Buildah
    # -------------------------
    - name: s2i-build
      runAfter:
        - build

      taskRef:
        name: s2i-dotnet-build

      params:
        - name: S2I_IMAGE
          value: "$(params.S2I_IMAGE)"

        - name: BUILDER_IMAGE
          value: "$(params.S2I_BUILDER_IMAGE)"

        - name: BUILDAH_IMAGE
          value: "$(params.BUILDAH_IMAGE)"

        - name: APPLICATION_IMAGE
          value: "$(params.APPLICATION_IMAGE)"

        - name: PROJECT_PATH
          value: "$(params.PROJECT_PATH)"

      workspaces:
        - name: source
          workspace: shared-workspace
