apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  generateName: pipelinerun-
  namespace: cicd-poc

spec:
  serviceAccountName: poc-pipeline

  pipelineRef:
    name: dotnet-ci

  params:

    - name: GIT_URL
      value: "https://github.com/bheem-medi/bheemas-nutrients-backend.git"

    - name: GIT_REVISION
      value: "main"

    - name: DOTNET_IMAGE
      value: "quay.io/tekton_cicd/custom.dotnet-sdk-image:dotnet-70"

    - name: S2I_IMAGE
      value: "registry.redhat.io/source-to-image/source-to-image-rhel9:1.6.0"

    - name: S2I_BUILDER_IMAGE
      value: "quay.io/tekton_cicd/custom.dotnet-sdk-image:dotnet-70"

    - name: BUILDAH_IMAGE
      value: "registry.redhat.io/ubi9/buildah:latest"

    - name: APPLICATION_IMAGE
      value: "quay.io/tekton_cicd/bheemas-nutrients-backend:latest"

    - name: PROJECT_PATH
      value: "."

  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: cicd-workspace
